import java.io.File;
import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.Scanner;

import Model.Item;

public class TestModel {

	//private String input;
	private String output;
	
	//Creating array list for room objects to be stored
	public static ArrayList<Room> rooms = new ArrayList<>();
	

	/**
	 * This part is to read in the room file and save each room object in an arrayList 
	 */
	
	File roomFile = new File("roomFile.txt");
	// open a Scanner to read data from File
	
	Scanner roomReader = null;  
	{
   try
	{
      roomReader = new Scanner(roomFile);
	
  } 
	catch (FileNotFoundException e)
  {
      System.out.println("File not found - terminating program");
      System.exit(0);
  	e.printStackTrace();
  }
  

   //Read room into array list
    while (roomReader.hasNext())
    {
    	// read room
    	String rID = roomReader.nextLine();
    	String rName = roomReader.nextLine();
    	String description = roomReader.nextLine();
    	String doors = roomReader.nextLine(); 
    	String items = roomReader.nextLine(); 
    	String monsters = roomReader.nextLine(); 
    	
    	// create new Room instance
    	Room temps = new Room(rID, rName, description, doors, items, monsters);
    	
    	//adding Item objects
    	Item rItems = new Item();
    	rItems.setiName(items);
    	temps.setrItems(rItems);
    	
    	//adding Monster objects
    	Monster rMonsters = new Monster();
    	rMonsters.setName(monsters);
    	temps.setrMonsters(rMonsters);
    	
    	//adding whole temps object to rooms arrayList
    	rooms.add(temps);	    	
    	}

	}
	
	//Current Room!// 
	Room currentRoom = new Room(); 
	
	public TestModel() {
		//input = "";
		output = "";
		System.out.println("Constructed");
		
	}
//	public void setInput(String input) {
//		//this.input = input;
//	}
	
	public void setOutput(String output) {
		this.output = output;
	}
	
	public String getOutput() {
		return output;
	}
	
	public String update(String input) 
	{
		if (output.isEmpty()) 
		{
			output = "PLAYER: " + input + "\r\nThis output was generated by the model.";
		}
		else
		{
			output = output + "\r\nPLAYER: " + input + "\r\nThis output was generated by the model.";
		}

		if(input.contains("Go to"))
		{
			String roomID = input.substring(input.indexOf("o", 4) + 2, input.length()); 
			currentRoom = findRoom(roomID); 
			//output = output + "\r\n" + in;
			output = currentRoom.getrName() + "\r\n" + currentRoom.getrDescription();
		}
		
		return output;

	}
	
	//Method finds a room object based on its roomID 
	public static Room findRoom(String roomID)
	{
		for (Room obj: rooms)
		{
			if(obj.rID.equals(roomID))
			{
				return obj;
			}
		}
		return null;

	}
	
	
	
}
