
public class TestModel {

	//private String input;
	private String output;
	
	public TestModel() {
		//input = "";
		output = "";
		System.out.println("Constructed");
		
	}
//	public void setInput(String input) {
//		//this.input = input;
//	}
	
	public void setOutput(String output) {
		this.output = output;
	}
	
	public String getOutput() {
		return output;
	}
	
	public String update(String input) {
		if (output.isEmpty()) {
			output = "PLAYER: " + input + "\r\nThis output was generated by the model.";
		} else {
			output = output + "\r\nPLAYER: " + input + "\r\nThis output was generated by the model.";
		}
		return output;
	}
	
	
	
}
